default_config:

debugpy:
  start: false

http:
  server_port: 9126

stream:
  ll_hls: true
  part_duration: 0.75
  segment_duration: 2

logger:
  default: error
  logs:
    pysecspy: debug
    custom_components.securityspy: debug
